FROM oven/bun

WORKDIR /app

ENV DISCORD_TOKEN = YOUR_BOT_TOKEN
ENV CHANNEL_IDS = CHANNEL_IDS
ENV CHANNEL_LANGS = CHANNEL_LANGS
ENV WEBHOOK_IDS = WEBHOOK_IDS
ENV WEBHOOK_TOKENS = WEBHOOK_TOKENS
ENV TRANSLATE_APIURL = TRANSLATE_APIURL

COPY package.json .
RUN bun install

COPY . .

CMD ["bun", "index.js"]